"""The runtime observation function, checked against the thing it replaces.

Three claims are worth a test rather than a comment: the bottom-centre pixel does NOT
back-project to the robot's centre (so the correction has something real to remove), a
perfect reading corrected from the prior returns the pose that generated it, and the
equivalent-position rewrite gives bit-for-bit the same posterior as a general-H update.
"""

from __future__ import annotations

import math
from pathlib import Path

import numpy as np
import pytest

from reliability.contracts import CameraQuality
from reliability.fusion import MapObservation, joseph_update_2d
from reliability.projection import camera_model_from_world
from reliability.silhouette_observation import (
    equivalent_position_measurement,
    observation_jacobian,
    plausibility_reasons,
    predicted_ground,
    predicted_pixel,
)

WORLD = (
    Path(__file__).resolve().parents[2]
    / "src/sim/gazebo_worlds/worlds/warehouse_v2.world.sdf"
)
#: A pose in the south-west of the hall that camera A sees at a realistic working range.
POSE = (-5.0, -3.0, 0.5)


@pytest.fixture(scope="module")
def camera():
    if not WORLD.exists():
        pytest.skip(f"{WORLD} is not present")
    return camera_model_from_world(WORLD, include_name="external_camera")


def test_the_bottom_centre_pixel_does_not_back_project_to_the_robot_centre(camera):
    x, y, yaw = POSE
    landing = predicted_ground(camera, x, y, yaw)
    assert landing is not None
    miss = math.hypot(landing[0] - x, landing[1] - y)
    # If this were small the deployed assumption would have been harmless. It is not:
    # the silhouette bottom is generated by the body part nearest the camera.
    assert miss > 0.10, miss
    # ...and the miss points TOWARDS the camera, which is why it looks like a bias.
    to_camera = np.array([camera.cam_pos[0] - x, camera.cam_pos[1] - y])
    to_camera /= np.linalg.norm(to_camera)
    displacement = np.array([landing[0] - x, landing[1] - y])
    assert float(displacement @ to_camera) > 0.0


def test_a_perfect_reading_corrected_from_the_prior_returns_the_pose_that_made_it(camera):
    x, y, yaw = POSE
    z = predicted_ground(camera, x, y, yaw)
    covariance = ((4.0e-4, 0.0), (0.0, 4.0e-4))
    corrected = equivalent_position_measurement(z, covariance, camera, (x, y), yaw)
    assert corrected is not None
    z_eq, _r_eq, _jacobian = corrected
    assert math.hypot(z_eq[0] - x, z_eq[1] - y) < 1.0e-9


def test_the_correction_survives_a_quarter_metre_prior_error(camera):
    x, y, yaw = POSE
    z = predicted_ground(camera, x, y, yaw)
    uncorrected = math.hypot(z[0] - x, z[1] - y)
    worst = 0.0
    for dx, dy in ((0.25, 0.0), (-0.25, 0.0), (0.0, 0.25), (0.0, -0.25),
                   (0.18, 0.18), (-0.18, -0.18)):
        corrected = equivalent_position_measurement(
            z, ((4.0e-4, 0.0), (0.0, 4.0e-4)), camera, (x + dx, y + dy), yaw
        )
        assert corrected is not None
        z_eq = corrected[0]
        worst = max(worst, math.hypot(z_eq[0] - x, z_eq[1] - y))
    # The prediction is evaluated at a pose up to 25 cm wrong -- the operating condition,
    # since the filter never has the true pose -- and still beats the uncorrected reading
    # by an order of magnitude. This is the property that makes it deployable.
    assert worst < 0.1 * uncorrected, (worst, uncorrected)


def test_equivalent_measurement_reproduces_a_general_H_update(camera):
    x, y, yaw = POSE
    prior_mean = (x + 0.12, y - 0.07)
    prior_cov = ((0.0625, 0.01), (0.01, 0.04))
    r_xy = ((9.0e-4, 2.0e-4), (2.0e-4, 4.0e-4))
    z = predicted_ground(camera, x, y, yaw)

    corrected = equivalent_position_measurement(z, r_xy, camera, prior_mean, yaw)
    assert corrected is not None
    z_eq, r_eq, jacobian = corrected
    identity_form = joseph_update_2d(
        prior_mean,
        prior_cov,
        MapObservation(
            camera_id="camera_A", timestamp_s=0.0, xy_m=z_eq, covariance_m2=r_eq,
            quality=CameraQuality(camera_id="camera_A"),
        ),
    )

    # The general-H update, written out with no reuse of the code under test.
    h = np.asarray(jacobian, float)
    p = np.asarray(prior_cov, float)
    r = np.asarray(r_xy, float)
    predicted = np.asarray(predicted_ground(camera, prior_mean[0], prior_mean[1], yaw), float)
    innovation = np.asarray(z, float) - predicted
    gain = p @ h.T @ np.linalg.inv(h @ p @ h.T + r)
    mean_general = np.asarray(prior_mean, float) + gain @ innovation
    factor = np.eye(2) - gain @ h
    cov_general = factor @ p @ factor.T + gain @ r @ gain.T

    assert np.allclose(np.asarray(identity_form[0], float), mean_general, atol=1.0e-12)
    assert np.allclose(np.asarray(identity_form[1], float), cov_general, atol=1.0e-12)


def test_the_observation_jacobian_is_near_identity_but_not_identity(camera):
    jacobian = np.asarray(observation_jacobian(camera, *POSE), float)
    assert np.all(np.isfinite(jacobian))
    # Near identity, because moving the robot a centimetre moves its silhouette bottom
    # about a centimetre -- but not identity, which is exactly why fusing two cameras
    # needs it: each camera's map from pose to landing point is its own.
    assert np.linalg.norm(jacobian - np.eye(2)) > 1.0e-3
    assert np.linalg.norm(jacobian - np.eye(2)) < 0.6


def test_the_runtime_prediction_is_the_same_function_the_study_scores(camera):
    from unav_common.robot_hull import silhouette_bottom_centre

    assert predicted_pixel(camera, *POSE) == silhouette_bottom_centre(camera, *POSE)


def test_the_plausibility_gate_keeps_a_faithful_box_and_rejects_the_four_failures(camera):
    from unav_common.robot_hull import silhouette_box

    x, y, yaw = POSE
    u0, v0, u1, v1 = silhouette_box(camera, x, y, yaw)
    assert plausibility_reasons((u0, v0, u1, v1), camera, x, y, yaw) == []

    short = (u0, v0 + 0.5 * (v1 - v0), u1, v1)
    assert "too_short" in plausibility_reasons(short, camera, x, y, yaw)

    narrow = (u0, v0, u0 + 0.5 * (u1 - u0), v1)
    assert "width_mismatch" in plausibility_reasons(narrow, camera, x, y, yaw)

    # Bottom edge well ABOVE the predicted contact row: the contact point is hidden.
    occluded = (u0, v0, u1, v1 - 12.0)
    assert "bottom_edge_occluded" in plausibility_reasons(occluded, camera, x, y, yaw)

    at_border = (0.0, v0, u1, v1)
    assert "touches_border" in plausibility_reasons(
        at_border, camera, x, y, yaw, image_size=(camera.img_width, camera.img_height)
    )


def test_the_gate_reads_the_image_size_off_the_camera_model(camera):
    from unav_common.robot_hull import silhouette_box

    x, y, yaw = POSE
    _u0, v0, u1, v1 = silhouette_box(camera, x, y, yaw)
    # No image_size argument: the border test must still fire from the model's own size.
    assert "touches_border" in plausibility_reasons((0.0, v0, u1, v1), camera, x, y, yaw)
