"""The runtime observation function: what pixel a camera should see, given a pose.

The deployed pipeline used to assume that the detector's bottom-centre pixel back-projects
to the robot's **centre**.  It does not.  The bottom edge of a silhouette is generated by
whichever part of the body is nearest the camera, so the pixel back-projects to a point
between the robot's centre and the camera -- always towards the camera, and by an amount
that swings with heading.  Measured on all five ``warehouse_v2`` cameras over 423 held-out
poses, that assumption costs a 7.78 cm typical miss of which 6.34 cm is systematic, and it
is systematic in a way no per-frame noise model can represent: a filter fed those readings
needs 8.4x the covariance a zero-mean filter would need, and learning ``R`` on that path
produced a filter 9.7x too confident (NEES 129).

This module states the observation function instead of assuming it away:

    h_c(x, y, yaw) = bottom-centre pixel of the projected VISUAL HULL of the robot

zero fitted parameters -- the shape is the robot description, the camera is the world file.
Projected back to the floor by plain inverse perspective mapping, it becomes the ground
point ``h_ground``, and the innovation the filter should form is ``z - h_ground(x^-)``
rather than ``z - x^-``.

**Why this does not require touching the filter.**  The estimator here is written for
``H = I`` throughout -- ``joseph_update_2d``, ``sequential_kalman_update_2d`` and the
information-gain selector all assume the measurement *is* the position.  A general-``H``
update with innovation ``z - h(x^-)`` is algebraically identical to an ``H = I`` update fed

    z_eq = x^- + H^-1 (z - h(x^-))          R_eq = H^-1 R H^-T

because ``H^T R^-1 H = R_eq^-1`` and ``H^T R^-1 (z - h(x^-)) = R_eq^-1 (z_eq - x^-)``.  So
the correction lives entirely in front of the filter, the frozen four-camera study's update
path is bit-identical, and ``test_silhouette_observation.py`` checks the two formulations
agree numerically rather than trusting the algebra above.

**Nothing here reads ground truth.**  ``h_c`` needs a pose to predict from, and the pose it
uses is the filter's own prior -- the same belief the planner is already publishing.  The
plausibility gate below is likewise computed from ``h_c(x^-)`` and the detected box alone.
That is what makes this deployable: no simulator state, no oracle visibility, no true pose.
"""

from __future__ import annotations

import math

Matrix2x2 = tuple[tuple[float, float], tuple[float, float]]

#: Central-difference step for ``dh/d(x, y)``.  Well inside the range where the silhouette
#: bottom is smooth in the pose, and well outside pixel quantization of the projection.
JACOBIAN_STEP_M = 0.02

#: Refuse to invert an observation Jacobian worse conditioned than this.  Near a degenerate
#: viewing geometry ``H^-1`` amplifies the reading instead of correcting it, and the honest
#: answer is to leave the sighting uncorrected rather than to trust a huge gain.
MAX_JACOBIAN_CONDITION = 20.0

#: D4's plausibility gate.  Keeps 68% of sightings and what survives is already
#: conditionally zero-mean with no bias model (worst conditional mean 0.86 cm).  The width
#: test is what removes the tail: a robot clipped sideways by a rack end keeps a correct
#: bottom row and a displaced horizontal centre.
MIN_HEIGHT_RATIO = 0.85
MAX_WIDTH_RATIO_ERROR = 0.10
MAX_BOTTOM_GAP_PX = 3.0
BORDER_MARGIN_PX = 1.0


def predicted_pixel(camera, x: float, y: float, yaw: float, points=None):
    """``h_c`` in pixels, or ``None`` when no part of the robot is in front of ``camera``."""

    from unav_common.robot_hull import VISUAL_HULL, silhouette_bottom_centre

    return silhouette_bottom_centre(
        camera, float(x), float(y), float(yaw), VISUAL_HULL if points is None else points
    )


def predicted_ground(camera, x: float, y: float, yaw: float, points=None):
    """``h_c`` pushed back to the floor by plain IPM: where the reading should land."""

    pixel = predicted_pixel(camera, x, y, yaw, points)
    if pixel is None:
        return None
    landing = camera.pixel_to_world(pixel[0], pixel[1])
    if landing is None:
        return None
    return float(landing[0]), float(landing[1])


def observation_jacobian(
    camera,
    x: float,
    y: float,
    yaw: float,
    *,
    step_m: float = JACOBIAN_STEP_M,
    points=None,
) -> Matrix2x2 | None:
    """``dh_ground/d(x, y)``: how the predicted landing point moves when the robot does.

    Two cameras do not measure the same thing -- each measures its own silhouette landing
    point -- so any update that fuses them needs this, not an assumed identity.  Heading is
    held fixed: the filter's yaw is an input to the prediction, not a state this 2-D update
    corrects.
    """

    step = float(step_m)
    if not math.isfinite(step) or step <= 0.0:
        raise ValueError("step_m must be finite and positive")
    columns = []
    for axis in (0, 1):
        dx = step if axis == 0 else 0.0
        dy = step if axis == 1 else 0.0
        plus = predicted_ground(camera, x + dx, y + dy, yaw, points)
        minus = predicted_ground(camera, x - dx, y - dy, yaw, points)
        if plus is None or minus is None:
            return None
        columns.append((
            (plus[0] - minus[0]) / (2.0 * step),
            (plus[1] - minus[1]) / (2.0 * step),
        ))
    (dhx_dx, dhy_dx), (dhx_dy, dhy_dy) = columns
    return ((dhx_dx, dhx_dy), (dhy_dx, dhy_dy))


def equivalent_position_measurement(
    z_xy: tuple[float, float],
    covariance_m2: Matrix2x2,
    camera,
    prior_xy: tuple[float, float],
    prior_yaw: float,
    *,
    step_m: float = JACOBIAN_STEP_M,
    max_condition: float = MAX_JACOBIAN_CONDITION,
    points=None,
):
    """Rewrite a silhouette reading as the position measurement an ``H = I`` filter wants.

    Returns ``(z_eq, R_eq, jacobian)``, or ``None`` when the prediction or its Jacobian is
    unavailable or too ill-conditioned to invert -- in which case the caller should use the
    uncorrected reading and say so, rather than apply a correction it cannot trust.
    """

    x_prior, y_prior = float(prior_xy[0]), float(prior_xy[1])
    if not all(math.isfinite(value) for value in (x_prior, y_prior, float(prior_yaw))):
        return None
    predicted = predicted_ground(camera, x_prior, y_prior, prior_yaw, points)
    if predicted is None:
        return None
    jacobian = observation_jacobian(
        camera, x_prior, y_prior, prior_yaw, step_m=step_m, points=points
    )
    if jacobian is None:
        return None
    inverse = _inverse_2x2(jacobian, max_condition=max_condition)
    if inverse is None:
        return None

    innovation = (float(z_xy[0]) - predicted[0], float(z_xy[1]) - predicted[1])
    step = _mat_vec(inverse, innovation)
    z_eq = (x_prior + step[0], y_prior + step[1])
    r_eq = _mat_mul(_mat_mul(inverse, covariance_m2), _transpose(inverse))
    r_eq = ((r_eq[0][0], 0.5 * (r_eq[0][1] + r_eq[1][0])),
            (0.5 * (r_eq[0][1] + r_eq[1][0]), r_eq[1][1]))
    if not all(math.isfinite(value) for row in r_eq for value in row):
        return None
    if not all(math.isfinite(value) for value in z_eq):
        return None
    return z_eq, r_eq, jacobian


def plausibility_reasons(
    box_uv: tuple[float, float, float, float],
    camera,
    x: float,
    y: float,
    yaw: float,
    *,
    image_size: tuple[int, int] | None = None,
    points=None,
) -> list[str]:
    """D4's four online checks on a detected box, given the prior pose.  Empty list = keep.

    Every quantity compares the detected box against ``h_c(x^-)``; none of them needs the
    true pose, the true visibility, or the simulator.  ``image_size`` is ``(width, height)``
    and defaults to the camera model's own, which is what the border test needs.
    """

    from unav_common.robot_hull import VISUAL_HULL, silhouette_box

    reasons: list[str] = []
    u0, v0, u1, v1 = (float(value) for value in box_uv)
    predicted = silhouette_box(
        camera, float(x), float(y), float(yaw),
        VISUAL_HULL if points is None else points,
    )
    if predicted is None:
        return ["no_prediction"]
    p_u0, p_v0, p_u1, p_v1 = predicted
    predicted_height = p_v1 - p_v0
    predicted_width = p_u1 - p_u0
    if predicted_height <= 0.0 or predicted_width <= 0.0:
        return ["degenerate_prediction"]

    if (v1 - v0) < MIN_HEIGHT_RATIO * predicted_height:
        reasons.append("too_short")
    if abs((u1 - u0) / predicted_width - 1.0) > MAX_WIDTH_RATIO_ERROR:
        reasons.append("width_mismatch")
    # A detected bottom edge ABOVE the predicted contact row means the contact point is
    # hidden, so the reading is short along the ray; below it is harmless perspective slack.
    if (p_v1 - v1) > MAX_BOTTOM_GAP_PX:
        reasons.append("bottom_edge_occluded")

    size = image_size
    if size is None:
        size = getattr(camera, "image_size", None)
        if size is None:
            width = getattr(camera, "img_width", None)
            height = getattr(camera, "img_height", None)
            size = None if width is None or height is None else (width, height)
    if size is not None:
        width, height = float(size[0]), float(size[1])
        margin = BORDER_MARGIN_PX
        if (u0 <= margin or v0 <= margin
                or u1 >= width - 1.0 - margin or v1 >= height - 1.0 - margin):
            reasons.append("touches_border")
    return reasons


def _inverse_2x2(matrix: Matrix2x2, *, max_condition: float) -> Matrix2x2 | None:
    a, b = float(matrix[0][0]), float(matrix[0][1])
    c, d = float(matrix[1][0]), float(matrix[1][1])
    determinant = a * d - b * c
    if not math.isfinite(determinant) or determinant == 0.0:
        return None
    # Frobenius/|det| stands in for the 2-norm condition number: cheap, never smaller than
    # the true ratio by more than sqrt(2), and it only ever rejects more, not less.
    norm = math.sqrt(a * a + b * b + c * c + d * d)
    if norm * norm / abs(determinant) > 2.0 * float(max_condition):
        return None
    return ((d / determinant, -b / determinant), (-c / determinant, a / determinant))


def _mat_mul(a, b):
    return (
        (a[0][0] * b[0][0] + a[0][1] * b[1][0], a[0][0] * b[0][1] + a[0][1] * b[1][1]),
        (a[1][0] * b[0][0] + a[1][1] * b[1][0], a[1][0] * b[0][1] + a[1][1] * b[1][1]),
    )


def _mat_vec(a, v):
    return (a[0][0] * v[0] + a[0][1] * v[1], a[1][0] * v[0] + a[1][1] * v[1])


def _transpose(a):
    return ((a[0][0], a[1][0]), (a[0][1], a[1][1]))
