"""Hit/miss expected-belief mixture in the CasADi EFE planner.

Two jobs here.

1. **Non-regression anchor.** ``R_plan`` precision-blending is FROZEN method for
   the published single-camera paper: ``honest_campaign_v1`` must stay
   reproducible bit-for-bit. ``test_flag_off_is_bit_identical_to_golden`` replays
   a fixed set of ``(u, m0, S0, goal, progress)`` points through the real
   ``make_efe_valgrad_fn`` with ``use_hit_miss_mixture=False`` and asserts exact
   float equality (``==``, not ``approx``) against values captured from the
   pre-change code. The golden literals below were generated by running this
   file's own harness against the unmodified ``casadi_efe.py``, so any drift in
   the frozen path fails here.

2. **Mixture semantics.** The mixture replaces "launder availability into R" with
   an honest two-branch expectation over a Bernoulli availability variable:
   with probability ``p_use`` a measurement arrives and the belief takes a full
   Kalman update with the *conditional* covariance ``R_cond``; with probability
   ``1 - p_use`` nothing arrives and the belief is unchanged. Tests pin the two
   endpoints, monotonicity in ``p_use``, and PSD-ness throughout.

All beliefs/fields here are synthetic test fixtures, not measurements.
"""

from __future__ import annotations

import math

import numpy as np
import pytest

ca = pytest.importorskip("casadi")

from planning.core import casadi_efe as cefe  # noqa: E402


# --------------------------------------------------------------------------
# Shared fixtures (deterministic; no file or artifact dependencies)
# --------------------------------------------------------------------------

def _camera_H() -> np.ndarray:
    """A concrete oblique-camera homography, so the golden numbers are realistic."""
    from unav_common.camera_model import ObliqueCameraModel

    cam = ObliqueCameraModel(
        cam_pos=(-5.0, -5.5, 4.8),
        look_at=(1.5, 1.5, 0.0),
        img_width=1280,
        img_height=720,
        fov_h_rad=1.2,
    )
    return np.asarray(cam.H, dtype=float)


def _p_vis_fixture():
    """Synthetic smooth availability field (a test fixture, not a fitted GP)."""
    s = ca.MX.sym("s", 3)
    val = 1.0 / (1.0 + ca.exp(-(1.2 * s[0] - 0.8 * s[1] + 0.5)))
    return ca.Function("p_vis_fixture", [s], [val], ["state"], ["p"])


def _nogo_belief_fixture():
    """Synthetic belief-aware no-go penalty (exercises the S_drive path)."""
    m = ca.MX.sym("m", 3)
    S = ca.MX.sym("S", 3, 3)
    val = ca.exp(-(m[0] ** 2 + m[1] ** 2)) * (1.0 + ca.trace(S))
    return ca.Function("nogo_belief_fixture", [m, S], [val], ["m", "S"], ["c"])


def _params(**overrides) -> cefe.CasadiEfeParams:
    base = dict(
        R_visible=np.diag([2.5 ** 2, 2.5 ** 2]),
        R_miss=np.diag([120.0 ** 2, 120.0 ** 2]),
        control_weight=0.05,
        risk_scale=1.25,
        ambiguity_scale=1.0,
        discount_gamma=0.98,
        process_noise_xy=0.05,
        process_noise_theta=0.03,
        visibility_sigma_kappa=1.0,
        goal_prior_u_std_start=80.0,
        goal_prior_v_std_start=80.0,
        goal_prior_u_std_final=18.0,
        goal_prior_v_std_final=18.0,
        goal_tightening_power=0.45,
        goal_progress_n_steps=90,
        use_belief_nogo_cost=False,
        time_horizon=6,
        dt=0.4,
        Du=2,
    )
    base.update(overrides)
    return cefe.CasadiEfeParams(**base)


# Fixed evaluation points: (u_flat, m0, S0, goal_obs, goal_xy, progress_index0).
_EVAL_POINTS = (
    (
        [0.30, 0.10, 0.35, -0.05, 0.40, 0.00, 0.25, 0.15, 0.30, -0.20, 0.20, 0.05],
        [-1.50, 0.75, 0.35],
        [[0.040, 0.006, 0.001], [0.006, 0.055, -0.002], [0.001, -0.002, 0.020]],
        [640.0, 380.0],
        [2.0, 1.0],
        12.0,
    ),
    (
        [-0.20, 0.40, 0.10, 0.30, 0.45, -0.25, 0.05, 0.35, -0.15, 0.20, 0.50, -0.10],
        [2.25, -1.40, -0.90],
        [[0.180, -0.030, 0.004], [-0.030, 0.110, 0.007], [0.004, 0.007, 0.060]],
        [300.0, 520.0],
        [-1.0, 2.5],
        45.0,
    ),
    (
        [0.50, 0.00, 0.50, 0.00, 0.50, 0.00, 0.50, 0.00, 0.50, 0.00, 0.50, 0.00],
        [0.10, 0.10, 1.57],
        [[0.010, 0.000, 0.000], [0.000, 0.010, 0.000], [0.000, 0.000, 0.005]],
        [900.0, 200.0],
        [3.5, -2.0],
        80.0,
    ),
)


def _golden_cases():
    """The (name, params, kwargs) configurations replayed by the golden test."""
    return (
        ("et1_vis", _params(), dict(approx="ET1", p_vis_state=_p_vis_fixture())),
        ("et2_vis", _params(), dict(approx="ET2", p_vis_state=_p_vis_fixture())),
        (
            "et1_vis_beliefnogo",
            _params(use_belief_nogo_cost=True),
            dict(
                approx="ET1",
                p_vis_state=_p_vis_fixture(),
                nogo_belief_cost=_nogo_belief_fixture(),
            ),
        ),
        ("et1_novis", _params(), dict(approx="ET1")),
    )


def _evaluate_case(params, kwargs):
    """Return [(objective, gradient_list), ...] over ``_EVAL_POINTS``."""
    valgrad = cefe.make_efe_valgrad_fn(params, _camera_H(), **kwargs)
    out = []
    for u, m0, S0, goal_obs, goal_xy, prog in _EVAL_POINTS:
        val, grad = valgrad(
            np.asarray(u, dtype=float),
            np.asarray(m0, dtype=float),
            np.asarray(S0, dtype=float),
            np.asarray(goal_obs, dtype=float),
            np.asarray(goal_xy, dtype=float),
            float(prog),
        )
        out.append((float(val), [float(g) for g in np.asarray(grad).reshape(-1)]))
    return out


# --------------------------------------------------------------------------
# Golden values captured from the PRE-CHANGE casadi_efe.py.
# Regenerate ONLY with an explicit decision to move frozen method:
#   python3 experiments/efe_hit_miss_mixture/regenerate_golden.py
# --------------------------------------------------------------------------
GOLDEN: dict[str, list[tuple[str, list[str]]]] = {
    'et1_vis': [
        ('0x1.dcb914e4647c6p+3', [
            '-0x1.51017cd972ee7p+1',
            '0x1.90030a6cce7f0p-1',
            '-0x1.07d792f922bbbp+1',
            '0x1.faba38521665fp-2',
            '-0x1.a3cc1e62e51eep+0',
            '0x1.f597c7e1dfc4dp-3',
            '-0x1.3598f06d62681p+0',
            '0x1.0b785e4e10242p-3',
            '-0x1.7bbf24968bdf2p-1',
            '0x1.b7dc788404b3cp-6',
            '-0x1.95db106be0a66p-2',
            '0x1.9f2409f0a6e2dp-11',
        ]),
        ('0x1.3541f08ca13c7p+8', [
            '0x1.424e50d9f0d56p+5',
            '-0x1.16afc438755efp+1',
            '0x1.0b9c96eafb5f2p+5',
            '-0x1.ed00b7d836f5bp+0',
            '0x1.a50489656ba8cp+4',
            '-0x1.a920e00dc55ddp-2',
            '0x1.472a7e83a805cp+4',
            '-0x1.446ba129ee473p-2',
            '0x1.a671dcbbc80f2p+3',
            '-0x1.386046c2e6eb7p-1',
            '0x1.a0662b148e85cp+2',
            '-0x1.9f2409f0a6e2dp-10',
        ]),
        ('0x1.1f240571c18c3p+8', [
            '0x1.168f21726609ep+4',
            '0x1.7fbf5c8f2dbf1p+4',
            '0x1.de339922455ccp+3',
            '0x1.ffc0a4a988222p+3',
            '0x1.8894befbd3833p+3',
            '0x1.3307658c87f90p+3',
            '0x1.2d2abc7147d73p+3',
            '0x1.32ede97e4d1f0p+2',
            '0x1.9997d24f59399p+2',
            '0x1.9900d0a275660p+0',
            '0x1.a0fdbf30a3ec5p+1',
            '0x0.0p+0',
        ]),
    ],
    'et2_vis': [
        ('0x1.dd6344ceeca70p+3', [
            '-0x1.51b93b05b3cfcp+1',
            '0x1.8f5376d9560b1p-1',
            '-0x1.0873af46e3146p+1',
            '0x1.f9d74acafea11p-2',
            '-0x1.a4c05398be14fp+0',
            '0x1.f4b29be135efcp-3',
            '-0x1.364ec2fc54e3fp+0',
            '0x1.0b02d5810c012p-3',
            '-0x1.7cb7c7a09442cp-1',
            '0x1.b6e4ffa775aeap-6',
            '-0x1.96c63f8315e36p-2',
            '0x1.9f2409f0a6e2dp-11',
        ]),
        ('0x1.35544546b237ep+8', [
            '0x1.430f5da87364ap+5',
            '-0x1.178c1cea0e21dp+1',
            '0x1.0c51657059320p+5',
            '-0x1.ee05708e2d22bp+0',
            '0x1.a64b5139d12fcp+4',
            '-0x1.ac4d4bf2bd500p-2',
            '0x1.48240eb3c65dep+4',
            '-0x1.45d2028298913p-2',
            '0x1.a7d5163c1c826p+3',
            '-0x1.3858300fa17fdp-1',
            '0x1.a22b82d4366b6p+2',
            '-0x1.9f2409f0a6e2dp-10',
        ]),
        ('0x1.1f341e682ef36p+8', [
            '0x1.16d760e0da167p+4',
            '0x1.7fddd8a484711p+4',
            '0x1.decba67b3e224p+3',
            '0x1.ffed99b50cba5p+3',
            '0x1.892757078b50ap+3',
            '0x1.33250a5d0bfbep+3',
            '0x1.2dab138c93f37p+3',
            '0x1.330e4e7acb98fp+2',
            '0x1.9a5af92b86e83p+2',
            '0x1.992fc7b04f00bp+0',
            '0x1.a1d85d52ba3a7p+1',
            '0x0.0p+0',
        ]),
    ],
    'et1_vis_beliefnogo': [
        ('0x1.e115ec1434668p+3', [
            '-0x1.47e435990576dp+1',
            '0x1.75dffdf335952p-1',
            '-0x1.00d6a46aadda4p+1',
            '0x1.d7ffa1e371686p-2',
            '-0x1.985466903df90p+0',
            '0x1.d214ed1e61ed0p-3',
            '-0x1.2d5f4f9c25418p+0',
            '0x1.f13a8c0a73060p-4',
            '-0x1.734163d0e02cap-1',
            '0x1.9221f9eb9001fp-6',
            '-0x1.8bac7e08bbc8ep-2',
            '0x1.9f2409f0a6e2dp-11',
        ]),
        ('0x1.35421e0e570cfp+8', [
            '0x1.424b75a1d9308p+5',
            '-0x1.16b03c9627dacp+1',
            '0x1.0b9a9f5a08e15p+5',
            '-0x1.ed012db3171d8p+0',
            '0x1.a5023939dd96bp+4',
            '-0x1.a920f1eb4f8ddp-2',
            '0x1.4728de1a4e9acp+4',
            '-0x1.446b597d5279fp-2',
            '0x1.a66fbf1dcafebp+3',
            '-0x1.386030df5d96fp-1',
            '0x1.a0651b3786c7fp+2',
            '-0x1.9f2409f0a6e2dp-10',
        ]),
        ('0x1.1fb025a6d185ap+8', [
            '0x1.122881b0b99bdp+4',
            '0x1.7ffacf2fdd625p+4',
            '0x1.d6a03fb4c9752p+3',
            '0x1.0002310d8f3b0p+4',
            '0x1.82b6fef52a772p+3',
            '0x1.33298fac912dfp+3',
            '0x1.29259b8506a97p+3',
            '0x1.330a44dc9d632p+2',
            '0x1.94eec212a1b8ap+2',
            '0x1.991ff419f8386p+0',
            '0x1.9d196131b4dbfp+1',
            '0x0.0p+0',
        ]),
    ],
    'et1_novis': [
        ('0x1.a95667b57277ap+3', [
            '-0x1.30b0551ef9e4ap+1',
            '0x1.5a7ccf5901907p-1',
            '-0x1.dd9df24672a21p+0',
            '0x1.b6cb126403217p-2',
            '-0x1.7b6f28ce1b761p+0',
            '0x1.b30575f9b0b57p-3',
            '-0x1.17d94e48b16eap+0',
            '0x1.d1fb0f5bbac70p-4',
            '-0x1.57f7c7bc7e6b2p-1',
            '0x1.765201ea37797p-6',
            '-0x1.6e79d536d78f5p-2',
            '0x1.9f2409f0a6e2dp-11',
        ]),
        ('0x1.353e60fefbc08p+8', [
            '0x1.425dd8cb46b17p+5',
            '-0x1.16addf6fa283ep+1',
            '0x1.0ba9301dd0094p+5',
            '-0x1.ecff5861cf503p+0',
            '0x1.a5176181762c4p+4',
            '-0x1.a922b46cd8addp-2',
            '0x1.47382ae692d76p+4',
            '-0x1.446fa604b7307p-2',
            '0x1.a683cdd9693bap+3',
            '-0x1.386262b804c4fp-1',
            '0x1.a0756067f0afcp+2',
            '-0x1.9f2409f0a6e2dp-10',
        ]),
        ('0x1.1e87ad1e75645p+8', [
            '0x1.14773f193ac3cp+4',
            '0x1.7dfd9abd7d880p+4',
            '0x1.da93c63fe8806p+3',
            '0x1.fd5d02c4b78d0p+3',
            '0x1.859466b2d3171p+3',
            '0x1.319169219808dp+3',
            '0x1.2ad8bd76903a2p+3',
            '0x1.3171262f614ccp+2',
            '0x1.966b1d97fa3d2p+2',
            '0x1.96fc7a8822028p+0',
            '0x1.9dbf7d3e6cff9p+1',
            '0x0.0p+0',
        ]),
    ],
}


def test_flag_off_is_bit_identical_to_golden():
    """The frozen precision-blend path must be untouched, to the last bit."""
    for name, params, kwargs in _golden_cases():
        assert not params.use_hit_miss_mixture, f"{name} must exercise the frozen path"
        expected = GOLDEN[name]
        actual = _evaluate_case(params, kwargs)
        assert len(actual) == len(expected)
        for idx, ((val, grad), (exp_val, exp_grad)) in enumerate(zip(actual, expected)):
            assert val == float.fromhex(exp_val), f"{name}[{idx}] objective drifted"
            assert len(grad) == len(exp_grad)
            for j, (g, exp_g) in enumerate(zip(grad, exp_grad)):
                assert g == float.fromhex(exp_g), f"{name}[{idx}] grad[{j}] drifted"


def test_mixture_flag_defaults_off():
    assert cefe.CasadiEfeParams.__dataclass_fields__["use_hit_miss_mixture"].default is False
    assert _params().use_hit_miss_mixture is False


def test_flag_on_changes_the_objective():
    """Sanity: the flag actually routes somewhere else (guards a dead flag)."""
    kwargs = dict(approx="ET1", p_vis_state=_p_vis_fixture())
    off = _evaluate_case(_params(), kwargs)
    on = _evaluate_case(_params(use_hit_miss_mixture=True), kwargs)
    assert any(a[0] != b[0] for a, b in zip(off, on))


def test_flag_on_never_reads_R_miss():
    """The mixture path must not depend on the unreconciled miss endpoint.

    ``MissEndpointPolicy`` blocks quoting 40 px vs 120 px; under the mixture the
    miss branch takes no update at all, so the constant must be irrelevant.
    """
    kwargs = dict(approx="ET1", p_vis_state=_p_vis_fixture())
    a = _evaluate_case(_params(use_hit_miss_mixture=True), kwargs)
    b = _evaluate_case(
        _params(use_hit_miss_mixture=True, R_miss=np.diag([40.0 ** 2, 40.0 ** 2])),
        kwargs,
    )
    for (va, ga), (vb, gb) in zip(a, b):
        assert va == vb
        assert ga == gb


# --------------------------------------------------------------------------
# Mixture semantics, exercised on the numeric helper directly
# --------------------------------------------------------------------------

_S_PRIOR = np.array(
    [
        [0.090, 0.020, 0.003],
        [0.020, 0.140, -0.006],
        [0.003, -0.006, 0.030],
    ]
)
_JAC = np.array([[420.0, -60.0, 0.0], [35.0, 380.0, 0.0]])
_R_COND = np.diag([2.5 ** 2, 2.5 ** 2])


def _mix_cov(p_use, S=_S_PRIOR, J=_JAC, R_cond=_R_COND):
    """Numeric evaluation of the symbolic mixture, via CasADi DM."""
    out = cefe.expected_posterior_cov_ca(
        ca.DM(np.asarray(S, dtype=float)),
        ca.DM(np.asarray(J, dtype=float)),
        ca.DM(np.asarray(R_cond, dtype=float)),
        ca.DM(float(p_use)),
    )
    return np.asarray(ca.DM(out))


def _hit_cov_numpy(S=_S_PRIOR, J=_JAC, R_cond=_R_COND):
    """Independent numpy reference for the hit branch (plain Schur form)."""
    S = np.asarray(S, dtype=float)
    J = np.asarray(J, dtype=float)
    Sigma = J @ S @ J.T + np.asarray(R_cond, dtype=float)
    K = S @ J.T @ np.linalg.inv(Sigma)
    return S - K @ (J @ S)


def test_mixture_at_p0_is_the_no_update_case():
    """p_use = 0: no measurement ever arrives, so the posterior IS the prior.

    Exactly the prior, not "the prior plus a regularisation floor": the Joseph
    construction needs no state-space floor, so the no-update branch is clean.
    """
    got = _mix_cov(0.0)
    assert np.allclose(got, _S_PRIOR, atol=1e-15, rtol=0.0)


def test_mixture_at_p1_is_the_full_update_case():
    """p_use = 1: the full Kalman update with R_cond, and nothing else."""
    got = _mix_cov(1.0)
    assert np.allclose(got, _hit_cov_numpy(), atol=1e-12, rtol=0.0)


def test_mixture_is_convex_combination_of_the_two_branches():
    hit = _mix_cov(1.0)
    for p in (0.0, 0.15, 0.37, 0.5, 0.82, 1.0):
        expected = p * hit + (1.0 - p) * _S_PRIOR
        assert np.allclose(_mix_cov(p), expected, atol=1e-14, rtol=0.0)


def test_mixture_trace_is_monotone_decreasing_in_p_use():
    ps = np.linspace(0.0, 1.0, 41)
    traces = [float(np.trace(_mix_cov(p))) for p in ps]
    diffs = np.diff(traces)
    assert np.all(diffs <= 1e-12), "more availability must never increase uncertainty"
    assert traces[0] > traces[-1]


def test_mixture_is_psd_throughout():
    for p in np.linspace(0.0, 1.0, 51):
        P = _mix_cov(p)
        assert np.allclose(P, P.T, atol=1e-12)
        eig = np.linalg.eigvalsh(0.5 * (P + P.T))
        assert eig.min() > 0.0, f"non-PD posterior at p_use={p}: min eig {eig.min():.3e}"


def test_mixture_psd_for_hard_priors():
    """Near-singular and strongly correlated priors must still yield a PD mixture."""
    hard = [
        np.diag([1e-6, 1e-6, 1e-6]),
        np.array([[0.5, 0.4999, 0.0], [0.4999, 0.5, 0.0], [0.0, 0.0, 1e-5]]),
        np.array([[2.0, 0.0, 1.4], [0.0, 2.0, 0.0], [1.4, 0.0, 1.0]]),
    ]
    for S in hard:
        for p in (0.0, 0.25, 0.5, 0.75, 1.0):
            P = _mix_cov(p, S=S)
            eig = np.linalg.eigvalsh(0.5 * (P + P.T))
            assert eig.min() > 0.0


def test_mixture_never_exceeds_the_prior_in_loewner_order():
    for p in np.linspace(0.0, 1.0, 21):
        delta = _S_PRIOR - _mix_cov(p)
        eig = np.linalg.eigvalsh(0.5 * (delta + delta.T))
        assert eig.min() >= -1e-9, "a measurement must never inflate the belief"


def test_expected_uncertainty_matches_branch_weighted_entropy():
    """The epistemic scalar is E[H], i.e. H(prior) - p_use * mutual information."""

    def ent(P):
        n = P.shape[0]
        return 0.5 * (n * math.log(2.0 * math.pi * math.e) + math.log(np.linalg.det(P)))

    h_prior = ent(_S_PRIOR)
    h_hit = ent(_hit_cov_numpy())
    for p in (0.0, 0.3, 0.61, 1.0):
        got = float(
            ca.DM(
                cefe.expected_posterior_uncertainty_ca(
                    ca.DM(_S_PRIOR), ca.DM(_JAC), ca.DM(_R_COND), ca.DM(float(p))
                )
            )
        )
        assert got == pytest.approx(p * h_hit + (1.0 - p) * h_prior, rel=1e-9, abs=1e-9)

    # information gain is non-negative, so the scalar is monotone decreasing
    assert h_hit <= h_prior


def test_expected_uncertainty_is_monotone_decreasing_in_p_use():
    vals = [
        float(
            ca.DM(
                cefe.expected_posterior_uncertainty_ca(
                    ca.DM(_S_PRIOR), ca.DM(_JAC), ca.DM(_R_COND), ca.DM(float(p))
                )
            )
        )
        for p in np.linspace(0.0, 1.0, 41)
    ]
    assert np.all(np.diff(vals) <= 1e-12)
    assert vals[0] > vals[-1]


def test_mixture_objective_is_differentiable_and_finite():
    """The whole point of staying symbolic: the NLP still gets a usable gradient."""
    params = _params(use_hit_miss_mixture=True)
    valgrad = cefe.make_efe_valgrad_fn(
        params, _camera_H(), approx="ET1", p_vis_state=_p_vis_fixture()
    )
    for u, m0, S0, goal_obs, goal_xy, prog in _EVAL_POINTS:
        val, grad = valgrad(
            np.asarray(u, dtype=float),
            np.asarray(m0, dtype=float),
            np.asarray(S0, dtype=float),
            np.asarray(goal_obs, dtype=float),
            np.asarray(goal_xy, dtype=float),
            float(prog),
        )
        assert math.isfinite(val)
        assert np.all(np.isfinite(grad))
        assert np.any(np.abs(grad) > 0.0)


def test_mixture_gradient_matches_finite_differences():
    """No symbolic branch sneaked in: autodiff agrees with central differences."""
    params = _params(use_hit_miss_mixture=True)
    valgrad = cefe.make_efe_valgrad_fn(
        params, _camera_H(), approx="ET1", p_vis_state=_p_vis_fixture()
    )
    u, m0, S0, goal_obs, goal_xy, prog = _EVAL_POINTS[0]
    u = np.asarray(u, dtype=float)
    args = (
        np.asarray(m0, dtype=float),
        np.asarray(S0, dtype=float),
        np.asarray(goal_obs, dtype=float),
        np.asarray(goal_xy, dtype=float),
        float(prog),
    )
    _, grad = valgrad(u, *args)
    h = 1e-6
    for i in range(u.size):
        up = u.copy()
        um = u.copy()
        up[i] += h
        um[i] -= h
        fd = (valgrad(up, *args)[0] - valgrad(um, *args)[0]) / (2.0 * h)
        assert fd == pytest.approx(grad[i], rel=2e-4, abs=2e-5)


def test_mixture_r_cond_defaults_to_r_visible_and_is_overridable():
    """R_cond default is documented as params.R_visible until a field is measured."""
    kwargs = dict(approx="ET1", p_vis_state=_p_vis_fixture())
    implicit = _evaluate_case(_params(use_hit_miss_mixture=True), kwargs)
    explicit = _evaluate_case(
        _params(use_hit_miss_mixture=True, R_cond=np.diag([2.5 ** 2, 2.5 ** 2])),
        kwargs,
    )
    for (va, ga), (vb, gb) in zip(implicit, explicit):
        assert va == vb
        assert ga == gb

    other = _evaluate_case(
        _params(use_hit_miss_mixture=True, R_cond=np.diag([9.0 ** 2, 6.0 ** 2])),
        kwargs,
    )
    assert any(a[0] != b[0] for a, b in zip(implicit, other))


def test_mixture_accepts_state_dependent_r_cond_and_bias():
    """Plumbing for a measured, spatially-varying R_cond(x) and bias b(x).

    Values here are placeholders: no field has been measured yet, so nothing is
    wired on by default. This only proves the hooks are symbolic and usable.
    """
    s = ca.MX.sym("s", 3)
    r_cond_state = ca.Function(
        "r_cond_fixture",
        [s],
        [ca.diag(ca.vertcat(4.0 + 0.5 * s[0] ** 2, 4.0 + 0.5 * s[1] ** 2))],
        ["state"],
        ["R"],
    )
    bias_state = ca.Function(
        "bias_fixture", [s], [ca.vertcat(0.3 * s[0], -0.2 * s[1])], ["state"], ["b"]
    )
    params = _params(use_hit_miss_mixture=True)
    valgrad = cefe.make_efe_valgrad_fn(
        params,
        _camera_H(),
        approx="ET1",
        p_vis_state=_p_vis_fixture(),
        R_cond_state=r_cond_state,
        obs_bias_state=bias_state,
    )
    u, m0, S0, goal_obs, goal_xy, prog = _EVAL_POINTS[0]
    val, grad = valgrad(
        np.asarray(u, dtype=float),
        np.asarray(m0, dtype=float),
        np.asarray(S0, dtype=float),
        np.asarray(goal_obs, dtype=float),
        np.asarray(goal_xy, dtype=float),
        float(prog),
    )
    assert math.isfinite(val)
    assert np.all(np.isfinite(grad))


def test_state_dependent_hooks_rejected_when_flag_off():
    """Guard: the frozen path must never silently accept mixture-only inputs."""
    with pytest.raises(RuntimeError, match="use_hit_miss_mixture"):
        cefe.make_efe_valgrad_fn(
            _params(),
            _camera_H(),
            approx="ET1",
            R_cond_state=_p_vis_fixture(),
        )
