#!/usr/bin/env python3
"""Generate the Gazebo Sim dynamic-actor variant of ``warehouse_aws``.

The base world remains the static benchmark.  This generator derives a separate
world that adds native Gazebo Sim ``TrajectoryFollower`` actors, so visual
dynamic-occlusion demonstrations do not alter existing experiments.
"""

from __future__ import annotations

from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
WORLDS = ROOT / "src" / "sim" / "gazebo_worlds" / "worlds"
BASE = WORLDS / "warehouse_aws.world.sdf"
OUTPUT = WORLDS / "warehouse_aws_dynamic.world.sdf"
MARKER = "<!-- DYNAMIC_ACTORS: generated by scripts/sim/generate_dynamic_warehouse_world.py -->"


def actor_model(
    name: str,
    *,
    size: tuple[float, float, float],
    colour: tuple[float, float, float],
    pose: tuple[float, float, float],
    waypoints: tuple[tuple[float, float], ...],
) -> str:
    x, y, yaw = pose
    sx, sy, sz = size
    r, g, b = colour
    points = "\n".join(f"          <waypoint>{px:.3f} {py:.3f}</waypoint>" for px, py in waypoints)
    return f"""
    <model name="{name}">
      <pose>{x:.3f} {y:.3f} {sz / 2:.3f} 0 0 {yaw:.3f}</pose>
      <link name="body">
        <gravity>false</gravity>
        <inertial><mass>45.0</mass><inertia>
          <ixx>4.0</ixx><iyy>4.0</iyy><izz>4.0</izz>
          <ixy>0</ixy><ixz>0</ixz><iyz>0</iyz>
        </inertia></inertial>
        <collision name="collision"><geometry><box><size>{sx:.3f} {sy:.3f} {sz:.3f}</size></box></geometry></collision>
        <visual name="visual"><geometry><box><size>{sx:.3f} {sy:.3f} {sz:.3f}</size></box></geometry>
          <material><ambient>{r:.3f} {g:.3f} {b:.3f} 1</ambient><diffuse>{r:.3f} {g:.3f} {b:.3f} 1</diffuse></material>
        </visual>
      </link>
      <plugin filename="gz-sim-trajectory-follower-system" name="gz::sim::systems::TrajectoryFollower">
        <link_name>body</link_name><loop>true</loop><force>100</force><torque>50</torque>
        <waypoints>
{points}
        </waypoints>
      </plugin>
      <!-- Publishes this actor's runtime pose for the D1 actor-track adapter. -->
      <plugin filename="gz-sim-pose-publisher-system" name="gz::sim::systems::PosePublisher">
        <publish_link_pose>true</publish_link_pose>
        <publish_collision_pose>false</publish_collision_pose>
        <publish_visual_pose>false</publish_visual_pose>
        <publish_nested_model_pose>false</publish_nested_model_pose>
      </plugin>
    </model>"""


def dynamic_actors() -> str:
    # Routes are deliberately in driveable lanes / cross-aisles and avoid the
    # static rack collision columns.  They are native geometry, not copied from
    # the external Gazebo-Classic scene.
    actors = (
        actor_model(
            "dynamic_worker_west", size=(0.45, 0.45, 1.70), colour=(0.23, 0.38, 0.95),
            pose=(-4.85, -2.70, 1.57), waypoints=((-4.85, -2.70), (-4.85, 4.35)),
        ),
        actor_model(
            "dynamic_forklift_apron", size=(0.95, 0.62, 1.25), colour=(0.92, 0.49, 0.06),
            pose=(-3.20, -2.72, 0.0), waypoints=((-3.20, -2.72), (4.45, -2.72)),
        ),
        actor_model(
            "dynamic_worker_north", size=(0.45, 0.45, 1.70), colour=(0.63, 0.23, 0.72),
            pose=(3.10, 4.35, 3.14), waypoints=((3.10, 4.35), (-3.10, 4.35)),
        ),
        actor_model(
            "dynamic_pallet_jack", size=(0.85, 0.48, 0.80), colour=(0.08, 0.65, 0.42),
            pose=(2.95, -0.35, 1.57), waypoints=((2.95, -0.35), (2.95, 3.80)),
        ),
    )
    return "\n".join((MARKER, *actors, ""))


def main() -> None:
    base = BASE.read_text(encoding="utf-8")
    if MARKER in base:
        raise RuntimeError("base world unexpectedly contains dynamic-actor marker")
    closing = "  </world>\n</sdf>"
    if closing not in base:
        raise RuntimeError(f"could not find world closing tag in {BASE}")
    dynamic = base.replace('<world name="warehouse_aws">', '<world name="warehouse_aws_dynamic">', 1)
    dynamic = dynamic.replace(closing, dynamic_actors() + closing, 1)
    OUTPUT.write_text(dynamic, encoding="utf-8")
    print(f"generated {OUTPUT.relative_to(ROOT)} with 4 looping actors")


if __name__ == "__main__":
    main()
