"""No tracked file may read from a path that only exists on one machine.

A deck figure once read its input from `/tmp/.../<session-id>/scratchpad/camdensity.json`
-- a previous session's scratch directory. The figure could not be regenerated by anyone,
including on the machine that made it, because the directory is deleted between sessions.
It went unnoticed because the path is not a word like TODO or HANDOFF; it looks like code.

An absolute path into /tmp, a home directory, or a session scratchpad means the artifact
is not reproducible from the repository, which is the one property every input to a result
has to have. Write outputs under `logs/`, read inputs from `logs/` or the repo, and locate
the root with `scripts/shared/paths.py: repo_root()`.
"""
from __future__ import annotations

import re
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parents[1]

#: Directories whose contents are tracked or are the reproducible surface of the project.
SEARCH_DIRS = ("src", "scripts", "experiments", "tests", "config", "schemas")

#: An absolute path that cannot exist on another machine.
MACHINE_LOCAL = re.compile(
    r"""["'](?:
          /tmp/            # scratch, deleted between sessions
        | /var/tmp/
        | /home/[A-Za-z0-9_.-]+/   # somebody's home directory
        | /Users/[A-Za-z0-9_.-]+/
    )[^"']*["']""",
    re.VERBOSE,
)

#: Legitimate uses: the tempfile module makes its own paths at runtime, and pytest's
#: tmp_path fixture is the sanctioned way for a test to need a scratch directory.
ALLOWED_LINE = re.compile(r"tempfile|TemporaryDirectory|tmp_path|mkdtemp|gettempdir")

#: A file that CREATES its own scratch directory and cleans it up is doing ordinary
#: staging, not depending on somebody else's leftovers. The failure this test exists for
#: is reading a path that had to be produced by a different process, on a different day.
#: A home directory is never acceptable either way -- it names one machine's user.
CREATES_OWN_SCRATCH = re.compile(r"mkdir -p /(?:var/)?tmp/|-o /(?:var/)?tmp/|-d /(?:var/)?tmp/")
HOME_PATH = re.compile(r"[\"'](?:/home/|/Users/)[A-Za-z0-9_.-]+/")


def _offending_lines(path: Path) -> list[str]:
    text = path.read_text(errors="replace")
    self_managed_scratch = bool(CREATES_OWN_SCRATCH.search(text))
    hits = []
    for number, line in enumerate(text.splitlines(), 1):
        stripped = line.strip()
        if ALLOWED_LINE.search(stripped):
            continue
        match = MACHINE_LOCAL.search(stripped)
        if not match:
            continue
        # a home directory pins the artifact to one user's machine, always
        if not HOME_PATH.search(stripped) and self_managed_scratch:
            continue
        hits.append(f"{path.relative_to(REPO)}:{number}: {stripped[:100]}")
    return hits


def test_no_tracked_source_reads_a_machine_local_path():
    offenders: list[str] = []
    for directory in SEARCH_DIRS:
        root = REPO / directory
        if not root.is_dir():
            continue
        for path in sorted(root.rglob("*")):
            if path.suffix not in (".py", ".yaml", ".yml", ".json", ".sh"):
                continue
            if "__pycache__" in path.parts or path.name == Path(__file__).name:
                continue
            offenders.extend(_offending_lines(path))
    assert not offenders, (
        "these read or write a path that exists only on one machine, so the artifact "
        "they produce cannot be reproduced from the repository:\n  "
        + "\n  ".join(offenders)
    )
