#!/usr/bin/env python3
"""Generate research/STATUS.md from research/registry.yaml."""

from __future__ import annotations

from pathlib import Path

from validate_registry import REGISTRY, ROOT, load_registry, validate


OUTPUT = ROOT / "research" / "STATUS.md"


def render(data: dict) -> str:
    experiments = data["experiments"]
    focus_id = data["current_focus"]["research_experiment_id"]
    focus = next(row for row in experiments if row["experiment_id"] == focus_id)
    maintenance_id = data["current_focus"]["maintenance_task_id"]
    maintenance = next(row for row in data["maintenance_tasks"] if row["id"] == maintenance_id)
    lines = [
        "<!-- GENERATED by scripts/research/build_status.py; do not edit manually. -->",
        "# Research status",
        "",
        f"Registry updated: `{data['updated']}`",
        "",
        "## Current focus",
        "",
        f"- Research: `{focus_id}` — {focus['title']}",
        f"- Gate: {focus['promotion_gate']}",
        f"- Next: {focus['next_action']}",
        f"- Maintenance: `{maintenance_id}` — {maintenance['title']}",
        f"- Maintenance next: {maintenance['next_action']}",
        "",
        "## Claims",
        "",
        "| ID | Status | Claim |",
        "|---|---|---|",
    ]
    lines.extend(f"| {row['id']} | {row['status']} | {row['statement']} |" for row in data["claims"])
    lines.extend(["", "## Experiments", "", "| ID | Status | Primary metric | Next action |", "|---|---|---|---|"])
    lines.extend(
        f"| {row['experiment_id']} | {row['status']} | {row['primary_metric']} | {row['next_action']} |"
        for row in experiments
    )
    lines.extend(["", "## Reviewer concerns", "", "| ID | Status | Concern |", "|---|---|---|"])
    lines.extend(f"| {row['id']} | {row['status']} | {row['concern']} |" for row in data["reviewer_questions"])
    return "\n".join(lines) + "\n"


def main() -> int:
    data = load_registry(REGISTRY)
    errors = validate(data, ROOT)
    if errors:
        for error in errors:
            print(f"ERROR: {error}")
        return 1
    OUTPUT.write_text(render(data), encoding="utf-8")
    print(f"Generated {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
